MODULES = jailed
include /Users/eskaseptian/Documents/theos/makefiles/common.mk

TWEAK_NAME = JooxPremium
DISPLAY_NAME = JooxPremium

JooxPremium_INJECT_DYLIBS = JooxPremium.dylib
JooxPremium_FILES = Tweak.xm
JooxPremium_IPA = /Users/eskaseptian/Desktop/HackedApp/jooxpremium/WeMusic_5.1.1_@Am1nCmd.ipa

include /Users/eskaseptian/Documents/theos/makefiles/tweak.mk